AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - config/**/*.rb
    - db/migrate/*.rb
    - db/schema.rb
    - db/seeds.rb
    - vendor/bundle/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/MutableConstant:
  AutoCorrect: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 7

Performance/RedundantMerge:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
