AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/MutableConstant:
  AutoCorrect: false

Metrics/ParameterLists:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 7

Performance/RedundantMerge:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
