# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          HANAMI_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ arch }}-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: RAILS_ENV=test bundle exec rake db:migrate

      # run unit tests
      - run:
          name: run unit tests
          command: |
            mkdir /tmp/test-results
            RAILS_ENV=test bundle exec rspec --exclude-pattern 'spec/features/*_spec.rb' \
                           --format documentation

      # run feature tests
      - run:
          name: run feature tests
          command: |
            RAILS_ENV=test COVERAGE_DIR=coverage_features bundle exec rspec --pattern 'spec/features/*_spec.rb' \
                           --format documentation

      # run rubocop
      - run: bundle exec rubocop -D

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: coverage
          destination: test-results
